name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodenv
        uses: nodenv/actions/node-version@master
        id: nodenv
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'
          cache: 'npm'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: bin/test
